### ISSUE TITLE
这能适配一下吗

### ISSUE THREAD

**Issue by fentianx** [Misuzu2027/syplugin-misuzu-custom#6]
![Image](https://github.com/user-attachments/assets/4f9473de-be4c-4cbd-a91d-6a7322ae4e31)

这个插件

![Image](https://github.com/user-attachments/assets/b24fc401-f2ce-49fa-bcd1-500ba4b2328f)

**Comment by Misuzu2027** [comment]
目前只会适配官方主题。其他主题和插件无法适配，不过可以用 自定义CSS 进行调整，我这里提供一个例子：
```css
/* 代码块名称输入框 */
.code-block .misuzu2027__copy.misuzu2027__protyle-custom[misuzu2027-code-block-naming] input{
	margin-left:80px;
    margin-top:-10px;
}

/* 代码块折叠按钮 */
.code-block .misuzu2027__copy.misuzu2027__protyle-custom[misuzu2027-code-block-toggle-button] {
    margin-top:-8px;
}
```
